# Generated by Django 5.2.5 on 2025-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='aboutMe',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description2',
            field=models.CharField(default='asdasd', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description3',
            field=models.CharField(default='asdasd', max_length=355),
        ),
    ]
