# Generated by Django 5.2.5 on 2025-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aboutme_aboutme_aboutme_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(default='', max_length=30)),
                ('project_Description', models.CharField(default='', max_length=255)),
                ('project_Tools', models.CharField(default='', max_length=15)),
                ('project_Link', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description3',
            field=models.CharField(default='', max_length=355),
        ),
    ]
