# Generated by Django 5.2.5 on 2025-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myproject_alter_aboutme_description2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_Name', models.CharField(default='', max_length=30)),
                ('skill_Items', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='myproject',
            name='project_Tools',
            field=models.CharField(default='', max_length=255),
        ),
    ]
