# Generated by Django 5.2.5 on 2025-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_myskill_alter_myproject_project_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_Name', models.CharField(default='', max_length=45)),
                ('award_Year', models.CharField(default='', max_length=45)),
                ('award_Description', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
