# Generated by Django 5.2.5 on 2025-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='myaward',
            name='award_Name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
