# Generated by Django 5.2.5 on 2025-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_myinformation_alter_myaward_award_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myinformation',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='myinformation',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
