# Generated by Django 5.2.5 on 2025-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contactformlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='helloMessage',
            field=models.CharField(default='Olá, Sou João Roberto', max_length=55),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='JR Portfolio ', max_length=22),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='welcomeMessage',
            field=models.CharField(default='Bem-vindo ao meu portfólio!', max_length=55),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='welcomeText',
            field=models.CharField(default='Sou um desenvolvedor de software com experiência em transformar ideias em soluções tecnológicas eficientes, sempre focado em melhorar a performance e a experiência do utilizado', max_length=255),
        ),
    ]
