# Generated by Django 5.2.5 on 2025-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_aboutme_hellomessage_aboutme_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='JR Portfolio', max_length=22),
        ),
    ]
